websites = {
    "youtube": "https://www.youtube.com/",
    "instagram": "https://www.instagram.com/",
    "facebook": "https://www.facebook.com/",
    "linkedin": "https://www.linkedin.com/",
    "github": "https://github.com/",
    "codeforces": "https://codeforces.com/",
    "youtube studio": "https://studio.youtube.com/",
    "netflix": "https://www.netflix.com/",
    "atcoder": "https://atcoder.jp/",
    "chatgpt": "https://chat.openai.com/",
    "spotify": "https://www.spotify.com/",
    "google": "https://www.google.com/",
    "reddit": "https://www.reddit.com/",
    "amazon": "https://www.amazon.com/",
    "wikipedia": "https://www.wikipedia.org/",
    "twitter": "https://twitter.com/",
    "twitch": "https://www.twitch.tv/",
    "dropbox": "https://www.dropbox.com/",
    "pinterest": "https://www.pinterest.com/",
    "whatsapp web": "https://web.whatsapp.com/",
    "discord": "https://discord.com/",
    "microsoft office": "https://www.office.com/",
    "stack overflow": "https://stackoverflow.com/",
    "medium": "https://medium.com/",
    "quora": "https://www.quora.com/",
    "apple": "https://www.apple.com/",
    "microsoft": "https://www.microsoft.com/",
    "slack": "https://slack.com/",
    "notion": "https://www.notion.so/",
    "trello": "https://trello.com/",
    "asana": "https://asana.com/",
    "zoom": "https://zoom.us/",
    "gitlab": "https://gitlab.com/",
    "hackerrank": "https://www.hackerrank.com/",
    "kaggle": "https://www.kaggle.com/",
    "coursera": "https://www.coursera.org/",
    "edx": "https://www.edx.org/",
    "udemy": "https://www.udemy.com/",
    "khan academy": "https://www.khanacademy.org/",
    "chess.com": "https://www.chess.com/",
    "duolingo": "https://www.duolingo.com/",
    "soundcloud": "https://soundcloud.com/",
    "bandcamp": "https://bandcamp.com/",
    "vimeo": "https://vimeo.com/",
    "figma": "https://www.figma.com/",
    "canva": "https://www.canva.com/",
    "unsplash": "https://unsplash.com/",
    "shutterstock": "https://www.shutterstock.com/",
    "adobe": "https://www.adobe.com/",
    "bbc": "https://www.bbc.com/",
    "cnn": "https://www.cnn.com/",
    "new york times": "https://www.nytimes.com/",
    "the guardian": "https://www.theguardian.com/",
    "al jazeera": "https://www.aljazeera.com/",
    "reuters": "https://www.reuters.com/",
    "bloomberg": "https://www.bloomberg.com/",
    "the verge": "https://www.theverge.com/",
    "hacker news": "https://news.ycombinator.com/",
    "product hunt": "https://www.producthunt.com/",
    "kickstarter": "https://www.kickstarter.com/",
    "indiegogo": "https://www.indiegogo.com/",
    "patreon": "https://www.patreon.com/",
    "imdb": "https://www.imdb.com/",
    "rotten tomatoes": "https://www.rottentomatoes.com/",
    "giphy": "https://giphy.com/",
    "airbnb": "https://www.airbnb.com/",
    "booking.com": "https://www.booking.com/",
    "expedia": "https://www.expedia.com/",
    "tripadvisor": "https://www.tripadvisor.com/",
    "yelp": "https://www.yelp.com/",
    "opentable": "https://www.opentable.com/",
    "grubhub": "https://www.grubhub.com/",
    "uber eats": "https://www.ubereats.com/",
    "doordash": "https://www.doordash.com/",
    "linkedin learning": "https://www.linkedin.com/learning/",
    "coursera": "https://www.coursera.org/",
    "codecademy": "https://www.codecademy.com/",
    "udacity": "https://www.udacity.com/",
    "code.org": "https://www.code.org/",
    "techcrunch": "https://techcrunch.com/",
    "wired": "https://www.wired.com/",
    "mashable": "https://mashable.com/",
    "engadget": "https://www.engadget.com/",
    "9gag": "https://9gag.com/",
    "imgur": "https://imgur.com/",
    "github pages": "https://pages.github.com/",
    "bitbucket": "https://bitbucket.org/",
    "digitalocean": "https://www.digitalocean.com/",
    "aws": "https://aws.amazon.com/",
    "google cloud": "https://cloud.google.com/",
    "azure": "https://azure.microsoft.com/",
    "heroku": "https://www.heroku.com/",
    "medium partner program": "https://medium.com/partner-program",
    "substack": "https://substack.com/",
    "wordpress": "https://wordpress.com/",
    "wix": "https://www.wix.com/",
    "squarespace": "https://www.squarespace.com/",
    "weebly": "https://www.weebly.com/",
    "shopify": "https://www.shopify.com/",
    "stripe": "https://stripe.com/",
    "paypal": "https://www.paypal.com/",
    "square": "https://squareup.com/",
    "stripe atlas": "https://stripe.com/atlas",
    "coinbase": "https://www.coinbase.com/",
    "binance": "https://www.binance.com/",
    "kraken": "https://www.kraken.com/",
    "etherscan": "https://etherscan.io/",
    "coinmarketcap": "https://coinmarketcap.com/",
    "crypto.com": "https://crypto.com/",
    "robinhood": "https://robinhood.com/",
    "etrade": "https://us.etrade.com/",
    "fidelity": "https://www.fidelity.com/",
    "vanguard": "https://www.vanguard.com/",
    "nerdwallet": "https://www.nerdwallet.com/",
    "mint": "https://www.mint.com/",
    "turbotax": "https://turbotax.intuit.com/",
    "h&r block": "https://www.hrblock.com/",
    "craigslist": "https://www.craigslist.org/",
    "indeed": "https://www.indeed.com/",
    "glassdoor": "https://www.glassdoor.com/",
    "monster": "https://www.monster.com/",
    "dice": "https://www.dice.com/",
    "ziprecruiter": "https://www.ziprecruiter.com/",
    "simplyhired": "https://www.simplyhired.com/",
    "linkedin jobs": "https://www.linkedin.com/jobs/",
    "behance": "https://www.behance.net/",
    "dribbble": "https://dribbble.com/",
    "artstation": "https://www.artstation.com/",
    "deviantart": "https://www.deviantart.com/",
    "creative market": "https://creativemarket.com/",
    "pixabay": "https://pixabay.com/",
    "pexels": "https://www.pexels.com/",
    "freepik": "https://www.freepik.com/",
    "etsy": "https://www.etsy.com/",
    "alibaba": "https://www.alibaba.com/",
    "aliexpress": "https://www.aliexpress.com/",
    "ebay": "https://www.ebay.com/",
    "walmart": "https://www.walmart.com/",
    "target": "https://www.target.com/",
    "home depot": "https://www.homedepot.com/",
    "lowe's": "https://www.lowes.com/",
    "best buy": "https://www.bestbuy.com/",
    "b&h photo video": "https://www.bhphotovideo.com/",
    "newegg": "https://www.newegg.com/",
    "costco": "https://www.costco.com/",
    "gamestop": "https://www.gamestop.com/",
    "steam": "https://store.steampowered.com/",
    "epic games store": "https://www.epicgames.com/store/",
    "gog": "https://www.gog.com/",
    "origin": "https://www.origin.com/",
    "uplay": "https://store.ubi.com/",
    "battle.net": "https://us.battle.net/",
    "playstation store": "https://store.playstation.com/",
    "xbox": "https://www.xbox.com/",
    "nintendo": "https://www.nintendo.com/",
    "fandango": "https://www.fandango.com/",
    "amc theatres": "https://www.amctheatres.com/",
    "cinemark": "https://www.cinemark.com/",
    "regal cinemas": "https://www.regmovies.com/",
    "eventbrite": "https://www.eventbrite.com/",
    "ticketmaster": "https://www.ticketmaster.com/",
    "stubhub": "https://www.stubhub.com/",
    "seatgeek": "https://seatgeek.com/",
    "opensea": "https://opensea.io/",
    "rarible": "https://rarible.com/",
    "foundation": "https://foundation.app/",
    "superrare": "https://superrare.com/",
    "zora": "https://zora.co/",
    "gemini": "https://www.gemini.com/",
    "nftx": "https://nftx.io/",
    "pancakeswap": "https://pancakeswap.finance/",
    "uniswap": "https://uniswap.org/",
    "sushiswap": "https://sushi.com/",
    "bitmex": "https://www.bitmex.com/",
    "bybit": "https://www.bybit.com/",
    "etoro": "https://www.etoro.com/",
    "stocktwits": "https://stocktwits.com/",
    "cryptoslate": "https://cryptoslate.com/",
    "cointelegraph": "https://cointelegraph.com/",
    "bitcoin magazine": "https://bitcoinmagazine.com/",
    "gizmodo": "https://gizmodo.com/",
    "polygon": "https://www.polygon.com/",
    "kotaku": "https://kotaku.com/",
    "gamespot": "https://www.gamespot.com/",
    "ign": "https://www.ign.com/",
    "destructoid": "https://www.destructoid.com/",
}
